name: FamLedger Web CI/CD to Azure
on:
  push:
    branches: [master]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: famledgerWeb
  NODE_VERSION: '22.x'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install dependencies
      working-directory: Famledger-frontend
      run: npm ci
      
    - name: Build Next.js (standalone)
      working-directory: Famledger-frontend
      run: npm run build

    - name: Prepare deployment folder
      working-directory: Famledger-frontend
      run: |
        mkdir deploy
        cp -r .next/standalone/* deploy/
        mkdir -p deploy/.next/static
        cp -r .next/static deploy/.next/static
        cp -r public deploy/public
        cp package.json deploy/
        cp package-lock.json deploy/

    - uses: actions/upload-artifact@v4
      with:
        name: next-app
        path: Famledger-frontend/deploy

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/download-artifact@v4
      with:
        name: next-app

    - uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEB_PUBLISH_PROFILE }}
        package: .
